name: continuous-integration
on: [pull_request, issues, push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: prettify
      uses: creyD/prettier_action@v2.2
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md}
        commit_message: made prettier 🦄
